### ISSUE TITLE
How to parse the raw_data for all stock symbols simultaneously?

### ISSUE THREAD

**Issue by Priyanshu-Mittal** [martinobdl/ITCH#6]
From the readme, it seems if we want to generate the output, we need to specify the stock symbol for which we want the output.
What if we want to generate output for all the stock symbols at once?

**Comment by martinobdl** [comment]
Sadly you have to run the program for each symbol. The reason is that messages regarding symbols you are not parsing are disregarded very quickly, and thus parsing two different symbols by calling will take approximately the same time of parsing the two symbols together. Moreover by allowing to parse multiple symbols at the same time we might incur in memory issues, since we have no control on the memory size of the data structures that will be generated by the program.

**Comment by Priyanshu-Mittal** [comment]
Okay, thanks
